backend:
  name: github
  repo: digital-ambernord-ch/decap-test-projekts
  branch: main
  auth_type: pkce
  app_id: TAVS_CLIENT_ID

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
