      backend:
  name: github
  repo: digital-ambernord-ch/decap-test-projekts
  branch: main
  base_url: https://github-oauth-proxy.eriksmatisonsvd.workers.dev

media_folder: images
public_folder: /images

collections:
  - name: pages
    label: Pages
    folder: content
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Body, name: body, widget: markdown}
